# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 822dd1bc2b793b8faf7826b0a967f63b289a4d1beaf9130202807d17315c78b7ae2473ac8aeaf84825ba81251920665fcd87ce975fa043f9f2ef175ee2314904

test:
  secret_key_base: ee12cf9264ee681b784fef137c5b7cff1c8ee4d2a39ed112f8da11a0ef8778121445121a132105f726826d8b7e76dddaae0f9544e3d3677994eb08c713bd4f47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
